# Generated by Django 5.0.6 on 2024-06-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sticky_notes_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPost",
            new_name="StickyNotes",
        ),
    ]
